### ISSUE TITLE
Model of the calculator? + etc.

### ISSUE THREAD

**Issue by puhitaku** [baltitenger/cgscreen#1]
Hi,

Thanks for an interesting work! Currently, I'm reverse-engineering an e-dictionary sold in Japan that has similar functionality (projector mode) and has the identical Vendor ID and Product ID (07cf:6101).

While cgscreen does not work with it currently (I've tried it), the way of communication should be similar so I'd like to analyze it and get it to work.

So I'd like to know:
 - The model of calculator you developed cgscreen for
 - Brief explanation of the way you reverse-engineered the communication (sorry for asking you this kind of thing but this must be super helpful!!)

Thanks in advance.

**Comment by puhitaku** [comment]
Mention for notification: @baltitenger

**Comment by baltitenger** [comment]
The calculator I've tried it with is the casio 9860GIII, but I think other people have tried it with others. I'm not the one who reverse engineered the protocol. The casio communiy calls it protocol 7 and they have libp7 and p7screen, my projec is based on this as well. [Here](https://www.planet-casio.com/Fr/forums/topic16648-last-linux-screen-receiver-kernel-module.html) is my post on their forum, where they have other useful resources as well. My driver should print what kind of error it is, if we're lucky it's just a different screen type. You could paste some dmesg as well.

**Comment by puhitaku** [comment]
Thanks for the detail. I read all posts in the forum and it helped me a lot to understand what's behind cgscreen.

When I connect the dictionary, a generic detection message appears and the kernel module outputs following lines in dmesg:

```
[15080419.830719] usb 1-3: new high-speed USB device number 26 using xhci_hcd
[15080419.979453] usb 1-3: New USB device found, idVendor=07cf, idProduct=6101, bcdDevice= 1.00
[15080419.979454] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[15080419.979455] usb 1-3: Product: CESG502
[15080419.979456] usb 1-3: Manufacturer: CASIO
[15080419.979456] usb 1-3: SerialNumber: 0123456789AB
[15080419.981945] cgscreen 1-3:1.0: Casio graphing device now attached.
[15080420.022338] cgscreen 1-3:1.0: Got non-image packet type, ignoring
```

A "non-image packet" (type ID != 0x0b) comes in first. Following is an output of p7screen with info level logging enabled:

```
[libp7 info]  p7_recv_main: received the following [normal] packet (6o) :
[libp7 info]  1644 4943 3030                          .DIC00
```

The command ID differs from 0x0b. `DIC00` looks a bit similar to `TYP01` and has no extra information. I modified p7screen to continue reading further bytes but no additional bytes come in. Maybe I have to tell something to my dictionary to complete the first negotiation as it postpones the connection saying "Failed to connect."

**Comment by baltitenger** [comment]
[This pdf](https://bible.planet-casio.com/simlo/fxreverse/fxReverse2.pdf) talks a lot about how protocol 7 works. It mentions acknowledgement and roleswap packets, maybe you need to send one of those. However, what you're getting seems to be different from anything mentioned in this document, so it might be the case that it doesn't use protocol 7 at all and just happens to have the same idVendor/idProduct combo. In any case, you should check what is being sent by the official screen receiver software (I'm not sure how that part is done).

**Comment by puhitaku** [comment]
Unfortunately, there's no official screen receiver software for PCs, so I'll have to grab a USB sniffer to achieve this. Anyway, now I know the backstory of this project and the model you used. Thanks for that, now I'm closing this.
